name = "llm-analyst"
main = "functions/scheduled-scrape.js"
compatibility_date = "2026-08-20"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "LLM_ANALYST_CACHE"
id = "697dd18ae9db458586b463006e2ddd5e"

[site]
bucket = "./static"

# Cron trigger: rescrape the Ollama library once per hour
[[triggers]]
crons = ["0 * * * *"]
